name: TomToTable
favicon: null
layout_spectrum: 0.49249
typography_spectrum: 0.67302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8E8D0'
    - '#106830'
    - '#000000'
    - '#70B040'
    - '#A0C870'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose:
  - name: follow
    item: null
    url: null
