analytics: {}
color:
  brandColors:
    - '#D8E8D0'
    - '#106830'
    - '#000000'
    - '#70B040'
    - '#A0C870'
  brandStrength: 1
  lightness: 0.75
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 0.49249
name: TomToTable
opengraph: {}
purpose:
  - name: follow
typography_spectrum: 0.67302
