name: TomToTable
favicon: null
layout_spectrum: 1
typography_spectrum: 0.273624176857993
title: Cooking blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#82be42'
    - '#106a37'
    - '#b0d688'
    - '#3c855b'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
